@startuml
'https://plantuml.com/class-diagram

Main -> Thymeleaf
Main -> Persistence
Persistence -> Thymeleaf
Persistence -> Exceptions
Persistence -> Entities

class Main {
-String USERNAME
-String PASSWORD
-String DB
-String URL
+void main(String args[])}
}

package Entities {
class Cupcake{
-CupcakeBottom bottom
-CupcakeTop top
-CupcakeTopping topping
}

abstract class CupcakeBottom {}
abstract class CupcakeTop {}
abstract class CupcakeTopping {}
}

package Exceptions {
class DatabaseException {}
}

package Persistence {
class ConnectionMapper {}

class DataMapper {}
}

package Thymeleaf {
class ThymeleafConfig{}
}


@enduml