@startuml
'https://plantuml.com/class-diagram

class Main

class User
class Cupcake
class Order

class CupcakeTopping
class CupcakeBottom




Main <-- User

User <-- Order

Order <-- Cupcake

Cupcake *-- CupcakeBottom
Cupcake *-- CupcakeTopping





@enduml